
package soapws.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "AlquilerSOAP", targetNamespace = "http://impl.soapws/", wsdlLocation = "http://localhost:8080/SOAP_war_exploded/alquiler?wsdl")
public class AlquilerSOAP
    extends Service
{

    private final static URL ALQUILERSOAP_WSDL_LOCATION;
    private final static WebServiceException ALQUILERSOAP_EXCEPTION;
    private final static QName ALQUILERSOAP_QNAME = new QName("http://impl.soapws/", "AlquilerSOAP");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SOAP_war_exploded/alquiler?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ALQUILERSOAP_WSDL_LOCATION = url;
        ALQUILERSOAP_EXCEPTION = e;
    }

    public AlquilerSOAP() {
        super(__getWsdlLocation(), ALQUILERSOAP_QNAME);
    }

    public AlquilerSOAP(WebServiceFeature... features) {
        super(__getWsdlLocation(), ALQUILERSOAP_QNAME, features);
    }

    public AlquilerSOAP(URL wsdlLocation) {
        super(wsdlLocation, ALQUILERSOAP_QNAME);
    }

    public AlquilerSOAP(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ALQUILERSOAP_QNAME, features);
    }

    public AlquilerSOAP(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlquilerSOAP(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AlquilerPORT
     */
    @WebEndpoint(name = "AlquilerSOAPImplPort")
    public AlquilerPORT getAlquilerSOAPImplPort() {
        return super.getPort(new QName("http://impl.soapws/", "AlquilerSOAPImplPort"), AlquilerPORT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlquilerPORT
     */
    @WebEndpoint(name = "AlquilerSOAPImplPort")
    public AlquilerPORT getAlquilerSOAPImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.soapws/", "AlquilerSOAPImplPort"), AlquilerPORT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ALQUILERSOAP_EXCEPTION!= null) {
            throw ALQUILERSOAP_EXCEPTION;
        }
        return ALQUILERSOAP_WSDL_LOCATION;
    }

}
