
package soapws.impl;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import soapws.interf.Cliente;
import soapws.interf.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "ClientePORT", targetNamespace = "http://interf.soapws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClientePORT {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCliente", targetNamespace = "http://interf.soapws/", className = "soapws.interf.CreateCliente")
    @ResponseWrapper(localName = "createClienteResponse", targetNamespace = "http://interf.soapws/", className = "soapws.interf.CreateClienteResponse")
    @Action(input = "http://interf.soapws/ClientePORT/createClienteRequest", output = "http://interf.soapws/ClientePORT/createClienteResponse")
    public Integer createCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteCliente", targetNamespace = "http://interf.soapws/", className = "soapws.interf.DeleteCliente")
    @ResponseWrapper(localName = "deleteClienteResponse", targetNamespace = "http://interf.soapws/", className = "soapws.interf.DeleteClienteResponse")
    @Action(input = "http://interf.soapws/ClientePORT/deleteClienteRequest", output = "http://interf.soapws/ClientePORT/deleteClienteResponse")
    public Integer deleteCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateCliente", targetNamespace = "http://interf.soapws/", className = "soapws.interf.UpdateCliente")
    @ResponseWrapper(localName = "updateClienteResponse", targetNamespace = "http://interf.soapws/", className = "soapws.interf.UpdateClienteResponse")
    @Action(input = "http://interf.soapws/ClientePORT/updateClienteRequest", output = "http://interf.soapws/ClientePORT/updateClienteResponse")
    public Integer updateCliente(
        @WebParam(name = "arg0", targetNamespace = "")
        Cliente arg0);

    /**
     * 
     * @return
     *     returns java.util.List<soapws.interf.Cliente>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readAllCliente", targetNamespace = "http://interf.soapws/", className = "soapws.interf.ReadAllCliente")
    @ResponseWrapper(localName = "readAllClienteResponse", targetNamespace = "http://interf.soapws/", className = "soapws.interf.ReadAllClienteResponse")
    @Action(input = "http://interf.soapws/ClientePORT/readAllClienteRequest", output = "http://interf.soapws/ClientePORT/readAllClienteResponse")
    public List<Cliente> readAllCliente();

    /**
     * 
     * @param arg0
     * @return
     *     returns soapws.interf.Cliente
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "readClienteById", targetNamespace = "http://interf.soapws/", className = "soapws.interf.ReadClienteById")
    @ResponseWrapper(localName = "readClienteByIdResponse", targetNamespace = "http://interf.soapws/", className = "soapws.interf.ReadClienteByIdResponse")
    @Action(input = "http://interf.soapws/ClientePORT/readClienteByIdRequest", output = "http://interf.soapws/ClientePORT/readClienteByIdResponse")
    public Cliente readClienteById(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

}
