
package soapws.impl;

import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;
import soapws.interf.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "HQLPORT", targetNamespace = "http://interf.soapws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HQLPORT {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "punto4", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto4")
    @ResponseWrapper(localName = "punto4Response", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto4Response")
    @Action(input = "http://interf.soapws/HQLPORT/punto4Request", output = "http://interf.soapws/HQLPORT/punto4Response")
    public List<Object> punto4(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "punto1", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto1")
    @ResponseWrapper(localName = "punto1Response", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto1Response")
    @Action(input = "http://interf.soapws/HQLPORT/punto1Request", output = "http://interf.soapws/HQLPORT/punto1Response")
    public List<Object> punto1(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "punto3", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto3")
    @ResponseWrapper(localName = "punto3Response", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto3Response")
    @Action(input = "http://interf.soapws/HQLPORT/punto3Request", output = "http://interf.soapws/HQLPORT/punto3Response")
    public List<Object> punto3(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "punto5", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto5")
    @ResponseWrapper(localName = "punto5Response", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto5Response")
    @Action(input = "http://interf.soapws/HQLPORT/punto5Request", output = "http://interf.soapws/HQLPORT/punto5Response")
    public List<Object> punto5(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        XMLGregorianCalendar arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        XMLGregorianCalendar arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "punto2", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto2")
    @ResponseWrapper(localName = "punto2Response", targetNamespace = "http://interf.soapws/", className = "soapws.interf.Punto2Response")
    @Action(input = "http://interf.soapws/HQLPORT/punto2Request", output = "http://interf.soapws/HQLPORT/punto2Response")
    public List<Object> punto2(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
